web_clicker:
  # Links
  website_link: https://www.sixdegreesofwikipedia.com/
  api_random_page: https://en.wikipedia.org/w/api.php?format=json&action=query&generator=random&grnnamespace=0&prop=revisions|images&rvprop=content&grnlimit=1

  # Web elements
  text_fields_class: "react-autosuggest__input"
  button_class: "bojiJp"
  blocks_class: "lazyload-wrapper "

  # Driver
  driver_path: driver/geckodriver

dataset_generator:
  most_frequent_words: internal/dataset_generator/inputs/most_frequent_words.txt

  dataset_path: internal/dataset_generator/output/dataset.csv
